### ISSUE TITLE
License for Gasp

### ISSUE THREAD

**Issue by jonathansick** [troelsfr/Gasp#5]
We think Gasp is neat and would like to investigate using it for [Large Synoptic Survey Telescope](http://lsst.org) documentation. Unfortunately, we can't legally do that until Gasp has a license.

Would you consider putting a license on this repo? See http://choosealicense.com Any open source license would make us happy.

If the code is licensed and we choose to use it on our doc stack, would you generally be receptive to pull requests from us for things like a `setup.py`, etc.?

**Comment by troels-im** [comment]
Sorry for my late reply. 

I've added a license - I suppose MIT will be fine, otherwise let me know and I can alter it.

Yes, I am happy to pull accept pull requests and as such, you and your team are free to push the library in any direction you see fit. Note that currently I have little time left next to work and family so I may occasionally not respond immediately to support requests.

**Comment by jonathansick** [comment]
thanks!
